const myarr=[0,1,2,3,4,5];
//console.log(myarr);
myarr.push(9);
myarr.pop();
//myarr.pop();
//console.log(myarr.includes(6));
//console.log(myarr.indexOf(5));
console.log("A",myarr);
const myn1=myarr.slice(1,3);
console.log(myn1);
console.log("B",myarr);
const myn2=myarr.splice(1,3);
console.log(myn2);
console.log("C",myarr);